print("Whats the name of the gift giver?")
name = raw_input()
print("What is the present they gave you?")
present = raw_input()
print("How old were you?")
age = int(raw_input())
print("What is your name?")
yname = raw_input()
print("Dear " + name + ",")
print("")
print("Thank you for the " + present + ".")
print("i really like it. I can't believe ")
print("I am already " + str(age) + " years old, but ")
print("it does not feel much different than being ")
print(str(age-1) + ".")
print("")
print("Sincerely,")
print(yname)
